DELETE FROM rcb.hop;
INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('Chinook \(20-1\)',CURRENT_DATE,'Billy Goat','BG ###',2021,16.40,7.82         );
INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('Citra \(19-2\)',CURRENT_DATE,'YCH','P91-DUCIT4128',2021,13.30,15.25          );
INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('Columbus \(20\)',CURRENT_DATE,'Hops Dir.','#111820399023',2021,14.00,6.68    );
INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('Columbus \(20-2\)',CURRENT_DATE,'','',2021,0,5.74                              );
INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('El Dorado \(19\)',CURRENT_DATE,'Mill 95','ELD19WO8',2021,15.10,11.30         );
INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('Falconers \(18\)',CURRENT_DATE,'YCH','P92-BJUFAL8097',2021,10.90,10.43       );
INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('Falconers\(20\)',CURRENT_DATE,'','',2021,0,   0                                      );
INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('Fuggle \(17\)',CURRENT_DATE,'YCH','17-0091',2021,4.20,11.75                  );
INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('EKG \(20\)',CURRENT_DATE,'YCH','P92-EEEKG0371',2021,5.90,11.79               );
INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('Galaxy \(18-041\)',CURRENT_DATE,'BSG','18P1GAX-VT041',2021,16.60,16.00       );
INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('Hallertau Blanc \(18\)',CURRENT_DATE,'MHA','18-436',2021,8.90,9.49           );
INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('Hallertau Blanc \(19-1\)',CURRENT_DATE,'YCH','19-399',2021,9.30,14.45        );
INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('Hallertau Blanc \(19-2\)',CURRENT_DATE,'YCH','19-620',2021,8.20,14.45        );
INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('Hersbrucker \(18\)',CURRENT_DATE,'YCH','18-136',2021,1.90,9.22               );
INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('Hersbrucker \(20\)',CURRENT_DATE,'Hollingberry','20-459',2021,4.20,8.92      );
INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('Idaho Gem \(19-1\)',CURRENT_DATE,'Mill95','GEM19WO1',2021,0,12.00              );
INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('Idaho Gem \(19-2\)',CURRENT_DATE,'Mill95','2561901',2021,13.00,12.00         );
INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('Magnum \(20\)',CURRENT_DATE,'MHA','MHA555-20MAG',2021,15.90,9.14             );
INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('Magnum \(20-2\)',CURRENT_DATE,'ProHops','20-043',2021,15.70,9.03             );
INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('Hallertau Mittelfrueh \(20\)',CURRENT_DATE,'Hopsteiner','',2021,0,0              );
INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('Mandarina Bavaria \(20\)',CURRENT_DATE,'HopHavoc','20-615',2021,8.30,10.73   );
INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('Mosaic \(18\)',CURRENT_DATE,'YCH','P91-CAUMOS3201',2021,12.50,13.95          );
INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('Motueka \(19\)',CURRENT_DATE,'BSG','19N2MOT11',2021,0,16.25                    );
INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('Motueka \(20\)',CURRENT_DATE,'BSG','20N1MOT11',2021,5.70,16.40               );
INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('Northern Brewer \(17\)',CURRENT_DATE,'YCH','17-574',2021,8.20,8.78           );
INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('Rakau \(20\)',CURRENT_DATE,'BSG','20N1RAK44',2021,8.60,14.75                 );
INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('Saaz \(20\)',CURRENT_DATE,'MHA','MHA ###',2021,2.60,11.63                    );
INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('Saaz \(20-1\)',CURRENT_DATE,'','',2021,0,12.08                                 );
INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('Simcoe \(20\)',CURRENT_DATE,'YCH','P91-EUSIM0286',2021,12.90,14.93           );
INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('Simcoe \(20-1\)',CURRENT_DATE,'','',2021,0,  0                                       );

INSERT INTO rcb.hop (name, date, supplier, lot_number, crop_year, price, alpha) VALUES ('temp 20-1',CURRENT_DATE,'','',0,  0                                       );
